//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminsetting
    {
        public int Id { get; set; }
        public int Taxpercent { get; set; }
        public string Companyname { get; set; }
        public string Address1 { get; set; }
        public string Adddress2 { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Hostname { get; set; }
        public string Smtpusername { get; set; }
        public string Smtpassword { get; set; }
        public string portno { get; set; }
        public Nullable<bool> Ismaintenance { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyEmail { get; set; }
        public string Utm_Source { get; set; }
        public string Utm_Medium { get; set; }
        public string Utm_Campaign { get; set; }
        public string Utm_Content { get; set; }
        public string Utm_Term { get; set; }
    }
}
