//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigMarkerUserDetail
    {
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> RegisteredUserId { get; set; }
        public string SeniorityLevel { get; set; }
        public string PrimaryJobFunction { get; set; }
        public string NatureOfBusiness { get; set; }
        public string Country { get; set; }
        public string TopicOfIntrest { get; set; }
        public string AreyouRegistered { get; set; }
        public Nullable<bool> OptInEmail { get; set; }
        public Nullable<bool> OptInPhone { get; set; }
        public Nullable<bool> OptInDirectEmail { get; set; }
        public Nullable<bool> OptInDGMEvents { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
