//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventMaster()
        {
            this.EventUsers = new HashSet<EventUser>();
            this.RegisteredUsers = new HashSet<RegisteredUser>();
        }
    
        public int EventId { get; set; }
        public string DomainName { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public string ResponseURL { get; set; }
        public int CustomerId { get; set; }
        public string Commentary { get; set; }
        public string ArticalUrl { get; set; }
        public string ArticalTitle { get; set; }
        public string LogoUrl { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public System.DateTime EventEndDate { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonEmail { get; set; }
        public string FormBuilderCode { get; set; }
        public Nullable<System.Guid> EventKey { get; set; }
        public string ButtonURL { get; set; }
        public string FbButtonURL { get; set; }
        public string GoogleButtonURL { get; set; }
        public string WebinarId { get; set; }
        public string ZoomToken { get; set; }
        public string ZoomUUID { get; set; }
        public string BigMarkerWebinairId { get; set; }
        public string BigMarkerToken { get; set; }
        public string HeySummitWebinarId { get; set; }
        public string HeySummitToken { get; set; }
        public string Channel { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventUser> EventUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisteredUser> RegisteredUsers { get; set; }
    }
}
