//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Orders = new HashSet<Order>();
            this.UserPackages = new HashSet<UserPackage>();
        }
    
        public int PackageId { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public decimal Cost { get; set; }
        public int Validity { get; set; }
        public int No_of_Registration { get; set; }
        public int No_of_Events { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime Updateddate { get; set; }
        public Nullable<decimal> Cost_per_Registration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPackage> UserPackages { get; set; }
    }
}
