//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisteredUser()
        {
            this.UserConnections = new HashSet<UserConnection>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public string Company { get; set; }
        public string JobDesignation { get; set; }
        public string MobileNumber { get; set; }
        public string ProfileLink { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<bool> Ispaid { get; set; }
        public Nullable<int> ReferalId { get; set; }
        public string ProfileId { get; set; }
        public string AuthToken { get; set; }
        public string CRM_FirstName { get; set; }
        public string CRM_LastName { get; set; }
        public string CRM_EmaiId { get; set; }
        public string CRM_CompanyName { get; set; }
        public string CRM_JobTitle { get; set; }
        public string CRM_RegistrationId { get; set; }
        public string Source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConnection> UserConnections { get; set; }
        public virtual EventMaster EventMaster { get; set; }
    }
}
