//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConnection
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ConnectionProfileId { get; set; }
    
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
